apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-alpine-k8s

spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nginx-alpine
  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
      - name: nginx
        image: meu_nginx:0.0.3
        ports:
        - containerPort: 80

